version: '3.8'

services:
  markitdown-service:
    build: .
    container_name: ${NETWORK_NAME:-murai-markitdown}
    pull_policy: build
    ports:
      - "7000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - ${NETWORK_NAME:-gptalk}

# If you need to create a custom network
networks:
  gptalk:
    name: ${NETWORK_NAME:-gptalk}
    external: true
