services:
  markitdown-service:
    build: .
    container_name: murai-markitdown
    pull_policy: build
    ports:
      - "7000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - markitdown-network

# If you need to create a custom network
networks:
  markitdown-network:
    name: ${NETWORK_NAME:-gptalk}
    external: true
